name: Build ratelimiting
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:bionic

    steps:
      - name: check docker container
        run: |
          pwd
          whoami
          
      - name: setup build dir
        run: |
          apt-get update
          apt-get install -y bc \
          bison \
          build-essential \
          clang \
          curl \
          exuberant-ctags \
          flex \
          gcc-8 \
          gcc-multilib \
          gnutls-bin \
          libc6-dev \
          libcurl4-openssl-dev \
          libelf-dev \
          libjson-c-dev \
          libncurses5-dev \
          libpcap-dev \
          libssl-dev \
          linux-headers-generic \
          linux-tools-common \
          linux-tools-generic \
          llvm \
          rsync \
          git-all
      
      - name: clone kernel
        run: |
          whoami
          ls -l / | grep usr
          chmod 777 /usr
          echo "After permission"
          ls -l / | grep usr
          #sudo chown -R $(whoami):$(whoami) /usr
          git clone --branch v5.1 --depth 1 https://github.com/torvalds/linux.git /usr/src/linux
          LINUX_SRC_DIR=/usr/src/linux
          cd $LINUX_SRC_DIR
          make defconfig

      - name: Clone repo
        uses: actions/checkout@v2

      - name: build ratelimiting
        run: |
          cd $GITHUB_WORKSPACE/../
          pwd
          cp -r ratelimiting /usr/src/linux/samples/bpf/
          cd /usr/src/linux/samples/bpf/ratelimiting
          git log
          ls
          make
          
